version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seatmap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - GIN_MODE=release

volumes:
  pgdata:
